### PR TITLE
feat: update ocm to latest including scheme fix

### PR DESCRIPTION
**Pull request by Skarlso**
Depends on https://github.com/open-component-model/ocm-e2e-framework/pull/29

Related to https://github.com/open-component-model/MPAS/issues/56

### CODE REVIEW

**Review by shivenduverma-sap — APPROVED** [review]

**Review by phoban01 — APPROVED** [review]

**Comment by Skarlso** [comment]
Uh, so this will take _some_ time. I'm refactoring to use a mock of the ocm context instead of trying to shoe horn something in with a butcher registry.

**Comment by Skarlso** [comment]
Alllll greeeen

**Review by phoban01 — APPROVED** [review]

**Comment by phoban01** [comment]
Just a note that this looks fine but it's not the latest ocm release.

**Comment by Skarlso** [comment]
>Just a note that this looks fine but it's not the latest ocm release.

Well, yes. :D It was the latest a week ago. :) The important part is that it contains the scheme fix in OCM.

**Pull request merged**
