### PR TITLE
fix: resourceRef should be a required property

### PR DESCRIPTION
**Pull request by Skarlso**
## Description

Closes https://github.com/open-component-model/ocm-project/issues/66

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

- Related Issue # (issue)
- Closes # (issue)
- Fixes # (issue)
> Remove if not applicable

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help
- [ ] Separate ticket for tests # (issue/pr)

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Added to documentation?

- [ ] 📜 README.md
- [ ] 🙅 no documentation needed

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by morri-son — APPROVED** [review]

**Comment by Skarlso** [comment]
Investigating test failure... interesting.

**Comment by Skarlso** [comment]
hm, it passes locally
```
Events:                                                                                                                            │
│   Type     Reason                    Age                    From            Message                                                │
│   ----     ------                    ----                   ----            -------                                                │
│   Warning  Progressing               5m10s                  ocm-controller  Reconciliation did not succeed, retrying in 5s         │
│   Warning  ComponentVersionNotReady  5m10s                  ocm-controller  component version not ready yet                        │
│   Normal   Succeeded                 4m19s (x11 over 5m9s)  ocm-controller  Reconciliation finished, next run in 5s                │
│   Normal   Succeeded                 8s (x61 over 5m9s)     ocm-controller  Applied version: 1.0.0
```

**Comment by Skarlso** [comment]
ah, that's not the right one. Found it:

```
{"level":"error","ts":"2024-05-02T13:29:50.069Z","msg":"Reconciliation failed after 54.435559ms, next try in 5s","controller":"kustomization","controllerGroup":"kustomize.toolkit.fluxcd.io","controllerKind":"Kustomization","Kustomization":{"name":"ocm-controller-tes │
│ t","namespace":"flux-system"},"namespace":"flux-system","name":"ocm-controller-test","reconcileID":"999620eb-1f68-4fdb-b228-c78c78183307","revision":"main@sha1:dc8ce138e2ca2aef26674366285aace1150dc627","error":"Configuration/ocm-system/configuration-pipeline-backend │
│  dry-run failed (Invalid): Configuration.delivery.ocm.software \"configuration-pipeline-backend\" is invalid: spec.sourceRef.resourceRef: Required value\n"}                      
```

Of course there was something without the resource thing. :D And here I was wondering what the hell would create a resource without a resource ref. :D

**Comment by Skarlso** [comment]
ah, I see why it's optional... If it's a component version it doesn't require a resource.

**Comment by Skarlso** [comment]
Ugh, I'm looking for a nicer way to do this. :D Because configRef also uses this. I wanted to create a Validation webhook, but all the scaffolding required seems overkill.

So I'm thinking of redesigning the API instead and using concrete values instead. I'll see what I can do tomorrow.

**Review by morri-son — APPROVED** [review]

**Pull request merged**
