### PR TITLE
feature: add flux install for ocm controller

### PR DESCRIPTION
**Pull request by Skarlso**
Closes https://github.com/open-component-model/ocm-controller/issues/510

### CODE REVIEW

**Comment by Skarlso** [comment]
_Almost_ working!

Screenshot 2024-09-20 at 19 30 22

**Comment by Skarlso** [comment]
This will come after I fix this https://github.com/open-component-model/ocm-controller/issues/509

**Review by morri-son — APPROVED** [review]
lgtm

**Comment by Skarlso** [comment]
There is still a slight problem that the ducking namespace isn't created arghhhh.

**Comment by Skarlso** [comment]
```
k get pods -A
NAMESPACE            NAME                                             READY   STATUS    RESTARTS   AGE
cert-manager         cert-manager-8598c8f746-dz6ng                    1/1     Running   0          3m20s
cert-manager         cert-manager-cainjector-6c8cbf8645-jbsxn         1/1     Running   0          3m20s
cert-manager         cert-manager-webhook-85567789f5-m24pv            1/1     Running   0          3m20s
flux-system          helm-controller-798cc88cb6-lnxvn                 1/1     Running   0          4m
flux-system          kustomize-controller-54df4985d-xx9wp             1/1     Running   0          4m
flux-system          notification-controller-66666bdd54-wf99d         1/1     Running   0          4m
flux-system          source-controller-588446b84b-knnwl               1/1     Running   0          4m
kube-system          coredns-5d78c9869d-l79g4                         1/1     Running   0          8m57s
kube-system          coredns-5d78c9869d-x5bql                         1/1     Running   0          8m57s
kube-system          etcd-ocm-test-control-plane                      1/1     Running   0          9m11s
kube-system          kindnet-59wq6                                    1/1     Running   0          8m58s
kube-system          kube-apiserver-ocm-test-control-plane            1/1     Running   0          9m13s
kube-system          kube-controller-manager-ocm-test-control-plane   1/1     Running   0          9m11s
kube-system          kube-proxy-czh57                                 1/1     Running   0          8m58s
kube-system          kube-scheduler-ocm-test-control-plane            1/1     Running   0          9m11s
local-path-storage   local-path-provisioner-6bc4bddd6b-jtssw          1/1     Running   0          8m57s
ocm-system           ocm-controller-85b7b7c98c-f7fgw                  1/1     Running   0          20s
ocm-system           registry-56d9bd8bf4-z7xm2                        1/1     Running   0          20s

```


FINALLY. Jesus.

**Pull request merged**
