### PR TITLE
feat: add subscription to the ComponentVersion

### PR DESCRIPTION
**Pull request by Skarlso**
## Description

Fixes https://github.com/open-component-model/ocm-project/issues/220

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

- Related Issue # (issue)
- Closes # (issue)
- Fixes # (issue)
> Remove if not applicable

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help
- [ ] Separate ticket for tests # (issue/pr)

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Added to documentation?

- [ ] 📜 README.md
- [ ] 🙅 no documentation needed

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Skarlso** [comment]
It seems to have worked 🎉 

```
2024-06-25T11:47:30Z info    [ocm/transfer] "transferring version" history=ocm.software/demos/podinfo:v1.0.1 ref=weave-gitops version=ocm.software/demos/weave-gitops:v1.0.0
2024-06-25T11:47:30Z info    [ocm/transfer] "  transferring references" history=ocm.software/demos/podinfo:v1.0.1 ref=weave-gitops version=ocm.software/demos/weave-gitops:v1.0.0
2024-06-25T11:47:30Z info    [ocm/transfer] "  transferring resources" history= version=ocm.software/demos/podinfo:v1.0.1
2024-06-25T11:47:31Z info    [ocm/transfer] "  transferring sources" history= version=ocm.software/demos/podinfo:v1.0.1
2024-06-25T11:47:31Z info    [ocm/transfer] "  adding component version" history= version=ocm.software/demos/podinfo:v1.0.1
```

And then the resources were fetched from the destination source rather than the source.

**Comment by Skarlso** [comment]
Podinfo is up and running.

```
default                      podinfo-5c98f69667-h98l8                            1/1     Running     0          2m41s
```

And the image has been replaced after the new version was published.

Screenshot 2024-06-25 at 13 50 42

**Comment by Skarlso** [comment]
ah, I need to update some documentation now.

**Review by morri-son — APPROVED** [review]
lgtm, but end-2-end tests are still failing

**Comment by Skarlso** [comment]
I think it was failing because of something unrelated, but I'll investigate anyways.

**Pull request merged**
