### PR TITLE
Add checking for dirty git tree after manifest and generate are run

### PR DESCRIPTION
**Pull request by Skarlso**

### CODE REVIEW

**Comment by Skarlso** [comment]
This action should fail on it's first run now because there are modifications in the tree that aren't committed.

**Comment by Skarlso** [comment]
Screenshot 2022-11-29 at 13 19 15

It failed. Now, I will add all the changes and this check should be passing.

**Comment by Skarlso** [comment]
Screenshot 2022-11-29 at 13 21 45
Yay 🎉

**Comment by phoban01** [comment]
Excellent, that KS for adding this 🎉

**Comment by Skarlso** [comment]
@phoban01 Thanks! :) Can you put a +1 on it, please? :)

**Review by phoban01 — APPROVED** [review]
LGTM

**Pull request merged**
