### PR TITLE
feat: upgrade Tiltfile hot reloading speed

### PR DESCRIPTION
**Pull request by Skarlso**

### CODE REVIEW

**Comment by Skarlso** [comment]
Hah I think I could load the result of the kustomization into a variable then do a string replace.

**Comment by Skarlso** [comment]
Ah! This https://docs.tilt.dev/templating.html alloys definitely improve things.

**Comment by Skarlso** [comment]
> Ah! This https://docs.tilt.dev/templating.html alloys definitely improve things. 

Yep. This is exactly what I was looking for. Patching the deployment before we apply it. Nice. I'll have an update on this later on.

**Comment by Skarlso** [comment]
yaaaay this worked. :)))

**Review by phoban01 — APPROVED** [review]

**Pull request merged**
